# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1376b0acfa0a6f2b6c8ac7dcd001665d767f2ed43a14b33c14479ccea378b670a6bcbd4e469037dd60a8a90dfcb319d1e35f21d6c2ae5f3b99b56520d8ee831a

test:
  secret_key_base: 69ba902217ab88d5184a64cf9af6cd76c9a81933c80b6ac424b2b50786c8ce19bb93c4fe9d2f95afa41aab6a1a977b73b8d57b5bc73d2d8e38b22bd382218962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
